env:
  token: "ENCRYPTED[!df122d4d9cfc211804e6184ff23e7eeb9e8b31df07f24e6dfa24901a68395f3a1723eb70db2ec3b1d2193841bc1108e2!]"

  chat_id: "ENCRYPTED[!aa2d76c404c234eaf041c246a927b86dd13ba093f5175cdcbd421d6b0b020074eea1a6427f4fa86b02506bb5f39372d9!]"


task:
  name: "Kernel Build.."
  timeout_in: 60m
  container:
    image: nexgang/ubuntu:latest
    cpu: 8
    memory: 32G
    stateful: true
    greedy: true
  Build_script:

    - sudo apt update
    - sudo apt upgrade -y
    - sudo apt install bc python2 pigz -y
    - mkdir -p /home/tc/zyc_clang
    - wget https://github.com/ZyCromerZ/Clang/releases/download/19.0.0git-20240320-release/Clang-19.0.0git-20240320.tar.gz
    - tar -xzvf Clang-19.0.0git-20240320.tar.gz -C /home/tc/zyc_clang
    - echo -e "\e[1;34mZYC Clang\e[0m \e[1;32mis set up successfully.\e[0m"
    - git clone --depth=1 https://github.com/mizdrake7/Graveyard_r5x -b 14 k
    - cd k
    - bash build.sh
    - echo -e "\e[1;32mKernel build successfully.\e[0m \e[1;36mFlash and enjoy!\e[0m"
